# Generated by Django 2.1.7 on 2019-03-21 18:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('is_publised', models.BooleanField(default=True)),
                ('main_photo', models.ImageField(upload_to='photos/listings')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/listings')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/listings')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/listings')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/listings')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/listings')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/listings')),
                ('published_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_mvp', models.BooleanField(default=False)),
                ('hire_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('profile_image', models.ImageField(upload_to='photos/realtors')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Realtor'),
        ),
    ]
